# Site settings
title: VizRob
email: mcampusa@dcc.uchile.cl
description: >
  VizRob is a set of visualizations for the execution of nested state machine using execution time and logs produced by the program.

# baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog/
url: https://mcamp.github.io/vizrob # the base hostname & protocol for your site
git_address: https://github.com/mcamp/vizrob
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Santiago
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
